AllCops:
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
